### ISSUE TITLE
should all files have a license header

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/playwright-dotnet#1575]
IMO it adds little value and too much noise, but many repos follow this approach. 

The current codebase is inconsistent, so what is your preference?

**Comment by pavelfeldman** [comment]
I think we want all source files to have a license header eventually.

@kblok can you help us sorting out the copyright headers?

It should be:
- "(c) Dario\nModifications by Microsoft" for the code we inherited from your PlaywrightSharp before our contract
- Copyright Microsoft for everything after our contract

If the transition to the driver happened during our contract, it is safe to swap API, Core, Transport, etc to be Microsoft. For the tests, we want Dario + Modifications by Microsoft because a lot of them survived the migration. But I don't remember it well @kblok !

**Comment by kblok** [comment]
I can complete the missing files based on that definition.
