### ISSUE TITLE
var or not?

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/playwright-dotnet#1580]
seems the current use of var is not consistent, what is your preference?

**Comment by pavelfeldman** [comment]
In my head, type inference is always contextual. Sometimes I want to have a short version, sometimes I want to declare the type to emphasize it for the reader.

**Comment by kblok** [comment]
It seems we removed that check [here](https://github.com/microsoft/playwright-dotnet/commit/1bf22238888819c62f24617422d836c3bc0d2d08#diff-8e113cdf6f7c10005985905922c1c2cbbdf6f4bb755e71eb48e043d2027760b2L48). @avodovnik do you remember why we removed that?

**Comment by avodovnik** [comment]
Yeah, I removed the check because it was annoying me with generated files - I wanted the generated code to always be the same, not have a check if the type is BCL or not. 

I agree with @pavelfeldman though, I sometimes pick one over the other, depending on the context. I think we _do_ need to make it more consistent, but I don't think it's a one-type-fits-all question.

**Comment by SimonCropp** [comment]
ok
