### ISSUE TITLE
[Feature]: Provide ability to pass CancellationToken into Async methods

### ISSUE THREAD

**Issue by FutureTD** [microsoft/playwright-dotnet#1652]
Is there a way to use cancellation tokens to cancel async operations?

It would be helpful to have most of the async methods able to be cancelled. Especially methods like

`await page.GotoAsync("https://github.com/");`

which would then be:

`await page.GotoAsync("https://github.com/", cancellationToken);`

**Comment by fr4gles** [comment]
Yea, it would be nice. 
In our project on some cases we are using "dirty task cancellation" similar to this https://devblogs.microsoft.com/pfxteam/how-do-i-cancel-non-cancelable-async-operations/

**Comment by mxschmitt** [comment]
Closing it, since there are no plans to support it. Browser interactions like clicks, fills are all not cancelable, so even if we would provide it, it would be a kinda fake cancel, and a certain action would still run in the background.

**Comment by schrufygroovy** [comment]
@mxschmitt this is true from a browser user perspective, but I think it's really not about cancelling any actions/commands but more about cancelling potential waiting process for the callbacks of the commands.

As far as I can see all commands are sent via `SendMessageToServerAsync()` - and for each command the callback is being awaited. Why should it not be reasonable to cancel this instead of waiting for callback to be fulfilled? For example when I want to cancel the execution (e.g: some test run, or some executable), why would I still need to wait until the `await page.GotoAsync("https://github.com/")` command is having some callback. I just want the execution to be stopped gracefully as fast as possible and no "hanging" execution.

I would really appreciate, if you would reconsider your decision or give us some alternative way to gracefully cancel pending commands.

**Comment by julealgon** [comment]
+1 on the request for reconsideration here @mxschmitt .

We started using Playwright last week and one of my first surprises was the lack of support for `CancellationToken` everywhere. The initial impression it gives is that the library is not a native C#/.NET library or that it is not as professional as other libraries in the ecosystem.

> Browser interactions like clicks, fills are all not cancelable, so even if we would provide it, it would be a kinda fake cancel, and a certain action would still run in the background.

This may well be the case, but _even the "fake" cancellation would be quite useful_, as you would still be able to cleanly terminate execution after some specific steps on a test instead of waiting until the entire test finishes, or forcing manual token checking on user code in-between library calls for cancellation.

I'd imagine most timeouts could support cancellation like @schrufygroovy , and even in cases where it doesn't have a _direct_ cancellation, a larger timeout check could be broken down into smaller timeouts internally with interspersed cancellation token checks (for example, a "30 second wait" could be done with 60 iterations of 500ms waits, each with a cancellation check).

Cancellation would be especially useful as test frameworks keep evolving (see `Microsoft.Test.Platform`) and more power is given to test framework authors and users which also extend to cancellation.

**Comment by kelmelzer** [comment]
+1 to work on this. I can help contribute with a PR if needed even.

Fwiw, I don't use the playwright test API but wire in playwright-dotnet for my custom remotely triggering framework factory and would love to send legit stop/cancel signals instead of doing hacky try/catch blocks waiting on timeouts or other exceptions from my remote closing of the Playwright browser in Selenium Grid and rethrowing as OperationCancelled/TaskCancelled exceptions.

I get the point that several *Async operations would be "fake" cancellable, but couldn't you just throw a token.ThrowIfCancellationRequested() on the first line of those methods anyway? Long running/polling-style methods would check more often obviously. I do that (even if its smelly or not) since it is generally pretty idiomatic in .NET to take and propagate CancellationTokens with its CancellationToken.Default being the default whenever you have a async methods.

**Comment by julealgon** [comment]
@kelmelzer 
> ...but couldn't you just throw a token.ThrowIfCancellationRequested() on the first line of those methods anyway? Long running/polling-style methods would check more often obviously. 

Yes. This would already be a very useful implementation here even if it wouldn't be possible to propagate the cancellation into the native layers.

> I do that (**even if its smelly** or not)

It is completely fine to do this, not a code smell at all. Cancellation is acceptable to use manually even in non-async code.

**Comment by kelmelzer** [comment]
Thanks for the backup. I may go on their Discord and do some squeaky wheel activity or volunteer the little free time I have to do a PR for this and/or sic an LLM on the task. :)
