### ISSUE TITLE
[Question]: How setup / code multi browser testing

### ISSUE THREAD

**Issue by apis3445** [microsoft/playwright-dotnet#1790]
### Your question

Is there an example to run tests cross-browser Playwright tests in parallel with CI/CD like azure devops? Or Do I need a third party-tool?

**Comment by apis3445** [comment]
but with nunit is only one browsser, doesn't include any option to run the same test with command line parameters some like 
dotnet test BROWSER=webkit chromium firefox
in the sample you need to execute the command 3 times

**Comment by Liero** [comment]
@apis3445: you can execute the test multiple times with different environment variable, as the browser type is determined by environment variable: https://github.com/microsoft/playwright-dotnet/blob/45de47f3f51c086278b347e09a878731d996e2e5/src/Playwright.NUnit/PlaywrightTest.cs#L33.

This is quite easy in CD pipelines, not so easy in local development environment as of now.

Alternatively, you can write tests class without inheriting from PageBase and create your own Playwright/Browser/Page instances.

You can use something like [[TestCaseSource]](https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html) attribute in NUnit, or  [ [DynamicData]](https://www.meziantou.net/mstest-v2-data-tests.htm#using-dynamicdata) in order to execute the same test with different parameter. In you case the parameter would be a browser name

**Comment by mxschmitt** [comment]
Closing since it seems answered. The recommended approach is execute it multiple times by invoking it multiple times via the CLI.

**Comment by apis3445** [comment]
In CI/CD you only have one environment variable, you will need one pipeline for each browser and url to test or run yhe pipelines a lot of times to setup. I was wondering only to use the same approach like saucelabs. The same test can run in parallel with different browsers

**Comment by Liero** [comment]
You can modify environment variable after each run in the same pipeline using .runsettings file.

Anyway, this is related to test runner, not so much to playwright (although I agree the environment variable should not be the only option to configure the test)

**Comment by apis3445** [comment]
But the environment is only for one test, at the moment the third party tools can't offer support to playwright for .net, and in the pipelines, I can't set up one pipeline to run in parallel in 4 browsers with 4 different environment, somethin like selenium grid too

**Comment by mxschmitt** [comment]
https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

That's e.g. how you can do it with GitHub Actions. Running them after each other is also a solution which works on every CI provider.

**Comment by Liero** [comment]
@apis3445 : you can pass different environment variables to each test run. Just google it

**Comment by apis3445** [comment]
I know how to passs different environment but I don't like to use one pipeline for each environment.
