### ISSUE TITLE
[Question]: Is it possible to modify a network response?

### ISSUE THREAD

**Issue by staind825** [microsoft/playwright-dotnet#1816]
### Your question

In the JS documents located [here](https://playwright.dev/docs/network/#modify-responses), I can see the ability to intercept a network response, modify it, then pass it along.

Is this possible in the .net library? If so could someone share an example?

**Comment by vflame** [comment]
doesn't appear to be working right. no way to read the response body  w/o locking up.
You can do a  `FulfillAsync` but that doesn't let you inspect the response. You can inspect the response with a `ContinueAsync` but then fulfill is ignored.

**Comment by mxschmitt** [comment]
You can, see here for examples: https://playwright.dev/dotnet/docs/network#modify-requests

For further questions, please open a new issue.

**Comment by staind825** [comment]
> You can, see here for examples: https://playwright.dev/dotnet/docs/network#modify-requests
> 
> For further questions, please open a new issue.

I am not looking to modify requests, I am looking to modify a network response before forwarding it on to the UI. I'd linked to the JS version of this in my original post but it seems like maybe that part has been removed from the JS documentation?

**Comment by Meir017** [comment]
the correct approach of sending a request through `APIRequestContext` looks like it would force us to buffer the entire response in order to pass it to `route.fulfill`.

I'm wondering if it would be possible to add metadata to the original response without intercepting it and buffering into memory the response object.

for example - modifying a response header of a 1GB file will force us to buffer all of the response in order to add a response header.

This might be an indicator that the test scenario is not an optimal one and should be optimized, I'm not sure about this :)
