### ISSUE TITLE
[Question]: Can action be automatically deployed to docker? Is there a script?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#1940]
### Your question

I can use docker, but I can't build it. Do you have relevant code?

**Comment by mxschmitt** [comment]
Playwright only supports Ubuntu 18/20. So if you use on of these containers, install the dependencies there using the CLI you should then be able to run your tests. See here for the relevant links:

- https://hub.docker.com/_/ubuntu
- https://playwright.dev/dotnet/docs/cli#install-system-dependencies
- https://playwright.dev/dotnet/docs/intro

Let us know if you have any concrete questions, since we are not able to assist you otherwise.
