### ISSUE TITLE
[Feature]frame locator should be also wait with timeout

### ISSUE THREAD

**Issue by coader** [microsoft/playwright-dotnet#1960]
now FrameByUrl & FrameLocator all execute immediately and not wait any seconds
so when multi tab app, use iframe to open new tab, it should delay and those method return no iframe

should it also wait until get frame or reach timeout?

**Comment by coader** [comment]
and IFrameLocator has no GetElementHandler method to get the instance, so can't judge if realy find frame object

**Comment by mxschmitt** [comment]
When using FrameLocator or Locator it won't query the DOM at all, these are just convenient wrappers and abstractions for accessing elements on the page. The actual querying happens when you call an action (click in this case), e.g.

`await page.FrameLocator("asf").Locator("asfasdf").ClickAsync();`

If you want to include a timeout (maximum amount of time to wait for the element to appear), you can do something like this:

```
await page.FrameLocator("asf").Locator("asfasdf").ClickAsync(new() { Timeout = 60000 });
```

**Comment by coader** [comment]
but framebyurl return iframe object, not locator

**Comment by mxschmitt** [comment]
It's expected that framebyurl does not wait, it will only search the current available frames by the URL and return its result.

What you can do is combine it with RunAndWaitForPageAsync see here: https://playwright.dev/dotnet/docs/pages#handling-new-pages
