### ISSUE TITLE
[Feature] .NET 6

### ISSUE THREAD

**Issue by OgreTransporter** [microsoft/playwright-dotnet#2015]
It would be good if Playwright was available not only for .NET5 but also for .NET6.

**Comment by mxschmitt** [comment]
Playwright supports .NET 6, do you experience any issues or in what kind of error does it end up?

**Comment by OgreTransporter** [comment]
Yes, I have already figured out how to make it work under .NET6. My intention was to update the `TargetFrameworks` in the projects.
```
<TargetFrameworks>netstandard2.0;net5.0</TargetFrameworks>
```
In other words, add net6.0 or replace 5 with 6.

**Comment by mxschmitt** [comment]
netstandard2.0 is there which net5 includes too.

Closing since we already work on net6.

**Comment by OgreTransporter** [comment]
.NET5 does not matter! EOL of .NET5 is May 8, 2022.

Proposal: replace net5.0 with net6.0 or remove net5.0 altogether.

**Comment by campersau** [comment]
The one benefit of switching to `net6.0` that I can see is that we can remove the explicit `System.Text.Json` reference for that since it is included in the BCL as well.
https://github.com/microsoft/playwright-dotnet/blob/74429bad8acc104f9a818ee594c81804d3b3eadd/src/Playwright/Playwright.csproj#L35

Similar to how I have done it for `Microsoft.Bcl.AsyncInterfaces` by adding `Condition="'$(TargetFramework)' == 'netstandard2.0'"`:
https://github.com/microsoft/playwright-dotnet/blob/74429bad8acc104f9a818ee594c81804d3b3eadd/src/Playwright/Playwright.csproj#L38

**Comment by mxschmitt** [comment]
We target only netstandard2.0 in the next version which should make it more clear. Closing since its answered.
