### ISSUE TITLE
[BUG] v1.19.0 is adding 50+ MB to my NuGet packages.

### ISSUE THREAD

**Issue by Xen0byte** [microsoft/playwright-dotnet#2022]
**Context:**
- Playwright Version: v1.19.0
- Operating System: Windows
- .NET version: .NET 6

**Describe the bug**

Building a NuGet package for my project with a reference to v1.18.1 creates a 68kb NUPKG, however building the exact same solution but with a reference to v1.19.0 creates a 51,840kb NUPKG.

**Comment by campersau** [comment]
I guess it is because of https://github.com/microsoft/playwright-dotnet/pull/1955 which now includes the node / package when doing a `dotnet pack`.
You can set `PlaywrightPlatform=none` either in the `.csproj` like
```xml
<PropertyGroup>
    <PlaywrightPlatform>none</Playwrightplatform>
</PropertyGroup>
```
or when running `dotnet pack /p:PlaywrightPlatform=none`.

https://playwright.dev/dotnet/docs/intro#bundle-drivers-for-different-platforms

**Comment by Xen0byte** [comment]
Aha, thanks @campersau, I must have missed this change in the recent changelogs. Please feel free to close this issue, if that is the intended behavior. 😊
