### ISSUE TITLE
NullReferenceException in NewContextAsync

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/playwright-dotnet#2071]
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.Playwright.Core.Browser.NewContextAsync(BrowserNewContextOptions options) in /_/src/Playwright/Core/Browser.cs:line 121
   at Microsoft.Playwright.Core.Browser.NewPageAsync(BrowserNewPageOptions options) in /_/src/Playwright/Core/Browser.cs:line 164
```

 * net6
 * `    <PackageReference Include="Microsoft.Playwright" Version="1.20.1" />`

```cs
using System.Threading.Tasks;
using Microsoft.Playwright;

class Program
{
    public static async Task Main()
    {
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync();
        var page = await browser.NewPageAsync();
        // ...
    }
}
```

offending line

https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright/Core/Browser.cs#L121

```
 ((Tracing)context.Tracing).LocalUtils = LocalUtils;
```

**Comment by SimonCropp** [comment]
seems BrowserContextInitializer.Tracing is deserialized as null 

<img width="729" alt="image" src="https://user-images.githubusercontent.com/122666/158775883-9d18906e-c58e-48ae-88b3-cc3f27f4b6ed.png">

**Comment by mxschmitt** [comment]
Is this maybe the same as https://github.com/microsoft/playwright-dotnet/issues/2069? Does it also happen on new projects?

**Comment by SimonCropp** [comment]
its weird. i cant repro in a new app. but i re-cloned my code and it still happens. this is the codebase that it fails in https://github.com/VerifyTests/Verify.HeadlessBrowsers

**Comment by slang25** [comment]
This threw me for a while, my issue was I needed to do a rebuild. It happens due to a mismatch of the JavaScript version and package version.
There's a few things that might help:
- a better error when this occurs. The current NRE doesn't explain what's wrong. There should be a correctness version check ahead of it here. Or at least an explicit null check with a message suggesting their might be a version mismatch (feels a little hacky)
- some msbuild smarts to not require a rebuild. Maybe the version number should go into the path so there's no chance of a stale dependency. Maybe a cache file in the obj folder that is used to record the version and force an update when needed?

I'd suggest a better null check on the tracing property (as consistency cannot be assumed due to too many moving parts), and the version number in the npm content that is copied to the bin folder.

**Comment by slang25** [comment]
I think we are hitting this known issue with the "fast update-to-date checker" https://github.com/dotnet/project-system/issues/4665

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/2069

**Comment by Joe118** [comment]
Still seeing this problem with NewContextAsync. I posted the details on #2069

**Comment by mxschmitt** [comment]
> Still seeing this problem with NewContextAsync. I posted the details on #2069 

Please file a new issue.

**Comment by Joe118** [comment]
Done, #2175
