### ISSUE TITLE
[Question]: Getting null when I run the custom javascript code using EvaluateAsync (v1.20.2)

### ISSUE THREAD

**Issue by Svemshetty** [microsoft/playwright-dotnet#2084]
### Your question
We have an angular application, I tried to run custom javascript code using EvaluateAync function, I always get a null value when it executes the code. 

 string cmd1 = "var chart = document.querySelector('[data-testId = \"burndown.chart\" ]');";
            string cmd2 = "var ngComp = ng.getComponent(chart);";
            string cmd3 = "var result = ngComp.labels;";
            string cmd4 = "eval(result);";

            string commandToExecute = cmd1 + cmd2+ cmd3+cmd4;

         
            var data = await _page.EvaluateAsync(commandToExecute);      

Any help is appreciated. 
Thank you,
Susmitha

**Comment by rwoll** [comment]
The following works for me:

```C#
using System.Threading.Tasks;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;

namespace PlaywrightTests
{
    [Parallelizable(ParallelScope.Self)]
    public class Tests : PageTest
    {
        [Test]
        public async Task ShouldMultiply()
        {
            int result = await Page.EvaluateAsync<int>(@"var a = 1; var b = 2; eval('3 + 4');");
            Assert.AreEqual(7, result);
        }
    }
}
```

So your `eval(result);` is likely evaluating to null or undefined which Playwright is dutifully returning.

To debug your script, you can try:

1. Open your browser and go directly to your page under test.
2. Open the Developer Console.
3. Manually run your commands and inspect the output. What does your final eval return when you do this manually?

Also, since it looks like your JS depends on an element being present, you should use [`Locator.EvaluateAsync`](https://playwright.dev/dotnet/docs/api/class-locator#locator-evaluate) instead of page's.
```

**Comment by rwoll** [comment]
It might be that the DOM is not fully rendered before you execute your evalute via Playwright.

Instead of:

```
var data = await _page.EvaluateAsync(commandToExecute);
```

Try using the following which should wait on the locator to resolve before executing:

```
var data = await _page.Locator("data-testId=burndown.chart").EvaluateAsync(commandToExecute);
```

Let us know if that works!

**Comment by Svemshetty** [comment]
No, It didn't work. I get the null value with the above snippet too.

**Comment by rwoll** [comment]
Please share a link to a minimal repo that we can clone and run that demonstrates your issue. Since https://github.com/microsoft/playwright-dotnet/issues/2084#issuecomment-1084096805 is working, we need more information to help debug.

**Comment by mxschmitt** [comment]
The reason why it's not working is that eval returns a class (BurndownChartComponent). A class is not JSON serializable, since the values need to get serialized from the browser JS context to the .NET world.

So you need to e.g. return a normal object, or just return isLoading value.

Also it seems like you don't need eval(). manually.

**Comment by Svemshetty** [comment]
I have tried without eval too. I had the same null issue.
string cmd1 = "var chart = document.querySelector('[data-testId = "burndown.chart" ]');";
string cmd2 = "var ngComp = ng.getComponent(chart);";
string cmd3 = "var result = ngComp.labels;";
string cmd4 = "result;";

        string commandToExecute = cmd1 + cmd2+ cmd3+cmd4;

     
        var data = await _page.EvaluateAsync<object>(commandToExecute);

**Comment by mxschmitt** [comment]
Sure, I didn't say `eval` is the issue, its just unnecessary. Try for example:

 ```c#
var burnDownChart = _page.Locator<object>("[data-testId='burndown.chart']");
var isLoading = burnDownChart.EvaluateAsync<bool>("chart => ng.getComponent(chart).isLoading");
```

We don't have a repro, so it's very hard for us to assist. To summarise so far: You need to pass JSON serialisable types over/return them, see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description). This is why null is returned.

**Comment by Svemshetty** [comment]
will try it out with loading. thank you.

**Comment by mxschmitt** [comment]
Closing as per above.
