### ISSUE TITLE
[Question]: is `playwright.ps1 install` needed if we have `<PlaywrightPlatform>`?

### ISSUE THREAD

**Issue by 304NotModified** [microsoft/playwright-dotnet#2100]
### Your question

Question:

Do I need to run `playwright.ps1 install` if I have this in my csproj? 

```xml
<PropertyGroup>
  <PlaywrightPlatform>linux</PlaywrightPlatform>
</PropertyGroup>
```
I do a dotnet publish. 

If not, then what's the benefit of `<PlaywrightPlatform>`?

(related: #2098, #2086)

**Comment by campersau** [comment]
Here is how I currently think Playwright works:

```mermaid
  flowchart TD
      subgraph language [Language Process]
      .NET
      Java
      Python
      end

      subgraph nodeprocess [Node.js Process]
      driver[Playwright Driver]
      linux -.- driver
      osx -.- driver
      win -.- driver
      end

      subgraph browserprocess [Browser Process]
      Chromium
      Firefox
      WebKit
      others[Chrome / Edge / others via WS / CDP]
      end

      language-- Playwright Protocol ---nodeprocess
      nodeprocess-- DevTools Protocol ----browserprocess

      style others stroke-dasharray: 5 5
```

Playwright Protocol: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/protocol/protocol.yml
DevTools Protocol: https://chromedevtools.github.io/devtools-protocol/

As you can see there are three different parts
1. The Playwright language specific code
2. The Playwright Node.js driver and Node.js runtimes for each platform
3. The Browsers

The `Microsoft.Playwright` NuGet package contains the Playwright .NET code (`Microsoft.Playwright.dll`) as well as the Node.js driver and a bundled Node.js runtimes for each platform. And because these Node.js runtimes are quite big (https://github.com/microsoft/playwright-dotnet/issues/1845) and you most likely only need one of them, we added a `PlaywrightPlatform` property (https://github.com/microsoft/playwright-dotnet/pull/1955) where you can specify which Node.js runtime you want.

The browsers on the other hand are not included in the NuGet package so you need to run `playwright.ps1 install` or `Microsoft.Playwright.Program.Main(new []{ "install" })` to download them. This isn't done automatically because they are even bigger and there are usecases where you don't need them like
- https://playwright.dev/dotnet/docs/browsers#google-chrome--microsoft-edge
- https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-connect
- https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-connect-over-cdp 

or you only need one of them like `playwright.ps1 install chromium` / `Microsoft.Playwright.Program.Main(new []{ "install", "chromium" })`.

**Comment by 304NotModified** [comment]
Excellent! Thanks!

**Comment by Cricam** [comment]
WOW... thanks
