### ISSUE TITLE
[Question]: Is the change to the result of EvaluateAsync expected in v1.23.0?

### ISSUE THREAD

**Issue by IsaacWalker** [microsoft/playwright-dotnet#2219]
### Your question

Howdy,

I'm working on a library for running [Axe in Playwright](https://github.com/IsaacWalker/PlaywrightAxeDotnet) for accessibility testing which works by using the evaluate API on a page to execute Deque's Axe and [deserializing the result to POCOs](https://github.com/IsaacWalker/PlaywrightAxeDotnet/blob/main/Playwright.Axe/AxeCoreWrapper/DefaultAxeCoreWrapper.cs#L92):

```cs
JsonElement? resultJsonElement = await page.EvaluateAsync($"(runOptions) => window.axe.run({contextParam}{runParamTemplate})", paramString);
```
Up until the bump the json element would be of this form:
```  json
ValueKind = Object : "{"testEngine":{"name":"axe-core","version":"4.4.3"},"testRunner":{"name":"axe"},"testEnvironment":{"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64
```

After bumping to v1.23.0:
```  json
ValueKind = Object : "{"$id":"1","testEngine":{"$id":"2","name":"axe-core","version":"4.4.3"},"testRunner":{"$id":"3","name":"axe"},"testEnvironment":{"$id":"4","userAgent":"Mozilla/5.0 (Window
```

Which is causing an issue now with deserialization. 
IsaacWalker/PlaywrightAxeDotnet#1

Is this response expected and should be handled on my end, or is this a regression?

**Comment by mxschmitt** [comment]
Playwright evaluation supports since 1.23 recursive objects when you serialize to or from JavaScript. This means that if you serialize to JsonElement, it will end up having `$id` attributes, the same way how .NET is doing it, see here: https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.referencehandler.preserve?view=net-6.0

You can either when serializing also enable preserve or serialize pass a Generic to EvaluateAsync which won't produce the $id attributes.
