### ISSUE TITLE
[Question] Unable to run api testing in dotnet 

### ISSUE THREAD

**Issue by shivshankar93** [microsoft/playwright-dotnet#2224]
I copied the complete code from the below page but am unable to run the test, I am knew to both C# and Playwright. 
https://playwright.dev/dotnet/docs/api-testing#complete-test-example

The 1st problem I face is that there is no main method to start the program
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS5001	Program does not contain a static 'Main' method suitable for an entry point	PlaywrightNew	C:\Users\suress\source\repos\PlaywrightNew\PlaywrightNew\CSC	1	Active

I created a class and added a new main method created an object of the TestGitHubAPI  class and then called the SetUpAPITesting()
I get an error where the Playwright object on this is null
Request = await this.Playwright.APIRequest.NewContextAsync

How do I instantiate and use the test apis.

I have included the Microsoft.Playwright and Microsoft.Playwright.NUnit packages what else do I need incase these are not enough

**Comment by mxschmitt** [comment]
This example is made when you are using the Playwright NUnit harness, see here for the introduction on how to get started: https://playwright.dev/dotnet/docs/intro

You can't just invoke the functions, since the context needs to be created etc. by NUnit and dotnet test needs to be used.

Alternatively you can use the library to get started: https://playwright.dev/dotnet/docs/library
