### ISSUE TITLE
Testing Support with xUnit

### ISSUE THREAD

**Issue by hishamco** [microsoft/playwright-dotnet#2244]
Is there a plan to support xUnit? If you can accept contribution I'm glad to push a PR

**Comment by mxschmitt** [comment]
We made a few experiments with xunit and turned out to be not that flexible in terms of parallelism etc. see here: https://playwright.dev/dotnet/docs/test-runners#xunit-support

Does it mean like it does not work with Playwright? No! It just means that we as of today don't provide our base classes for it.

We are currently in the process of improving the base classes (and then maybe we provide a third-party package for xunit, but not under the Microsoft name.)

**Comment by hishamco** [comment]
Thanks for response, seems I will create a fork and do it myself as OSS
