### ISSUE TITLE
[Question]: Differences between .NET and Node.js implementations

### ISSUE THREAD

**Issue by IkamG** [microsoft/playwright-dotnet#2301]
### Your question

Hello, we are looking to use Playwright and currently evaluating whether to move forward with the Node.js or .NET implementation. My understanding is that the performance between the various versions is similar.

We would prefer to use .NET; however, we were wondering if there was any documentation outlining the differences between the 2 versions, specifically in terms of features. For example I noticed that the .NET version does not support Chrome extensions.

**Comment by mxschmitt** [comment]
> My understanding is that the performance between the various versions is similar.

This is correct, the performance heavy part happens inside the browser. So there is not a huge difference between Node.js, .NET etc.

>  if there was any documentation outlining the differences between the 2 versions, specifically in terms of features

Our key goal is to make all features available on all the language bindings. Experimental or browser specific features (like Chrome extensions) are by that not available everywhere yet. But talking about chrome extensions, you can use them as of today already, you just don't have access to the backgroundPages - but you might be blocked on that. For the developer experience / test-runner side, we're working on improving the .NET experience significantly - stay tuned!

So if you have to decide as of today, what to choose, especially if your team already has experience in JavaScript, then we'd recommend our Node.js version with TypeScript (since its like JS and TS just provides more superpowers). This does not mean .NET is unusable, you just need to do some things manually, figure things out yourself, and there is a lack in documentation etc.

**Comment by IkamG** [comment]
Thank you @mxschmitt for the quick response.
