### ISSUE TITLE
[Feature] Reporting

### ISSUE THREAD

**Issue by licon4812** [microsoft/playwright-dotnet#2681]
# Reporting

I am planning on adding HTML reporting to the dotnet version of Playwright.

I am considering making the HtmlReporting a Blazor WASM project as it produces static files that can be handed to BAs.

The idea is to make it so that after a test/suite is run, the user can use ```playwright --show-report``` it uses the Blazor library instead of trying to use node js.

The idea is to have out-of-the-box reporting for Playwright dotnet without needing external libraries. 

## Why blazor and not react or vite?

The idea is to not have a dependency on node js as the people using the dotnet version of Playwright in the first place most likely don't want node in their tech stacks

**Comment by mxschmitt** [comment]
The difference between Playwright for .NET and Playwright for Node.js is that in .NET we don't have our own test-runner. This limits us in a lot of areas, e.g. we don't have retries, control about timeouts etc. I would recommend to start as an external open source project for now and see how much value it actually gives, since so far we are not opinionated if you are using NUnit or MSTest.

We neither have screenshots, videos, nor traces, nor test steps in .NET so I think its not worth exploring as of today.

Closing as blocked by https://github.com/microsoft/playwright-dotnet/issues/2214 and https://github.com/microsoft/playwright-dotnet/issues/2316
