### ISSUE TITLE
[Feature] WebView2?

### ISSUE THREAD

**Issue by LukeTOBrien** [microsoft/playwright-dotnet#2686]
Hello,

I haven't used Playwright for awhile but from what I can remember it is not purely C#/.NET, it requires NodeJS and Chromium binaries.  
I wonder, what would it take for Playwright to use [WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)?

One issue is that [WebView2 doesn't support off screen (headless)](https://github.com/MicrosoftEdge/WebView2Feedback/issues/547) but I think that for the .NET platform the use of WebView 2 would remove dependencies on NodeJS and it might be an idea for the future.

What do you think?

**Comment by mxschmitt** [comment]
Playwright for .NET/Python/Java is a language port which internally relies on Node.js yes. We have all our core logic inside the Node.js version of Playwright and re-use it by that. Moving this business logic to each of the language ports would be technically possible, but we don't plan to do it, since it would be an erroneous effort to main it, introduce bugs etc.

You don't need to install Chromium if you e.g. [connect via CDP](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-connect-over-cdp) to an existing CDP instance or use [Stable Chrome/Edge](https://playwright.dev/dotnet/docs/browsers#google-chrome--microsoft-edge) channels.

Regarding your question, is WebView2 a replacement for a Chromium browser? Sort of but with limitations, we have a guide of how to use WebView2 [here](https://playwright.dev/dotnet/docs/webview2). If you want to see a minimal example, see e.g. [this](https://github.com/microsoft/playwright/tree/main/tests/webview2) project which we use to run our tests inside WebView2 to make sure they pass there. You could copy this project and use it as your foundation of your testing harness. We don't recommend it tho, since you are testing something different to what your users are using, they are using a real browser.

**Comment by mxschmitt** [comment]
Closing as per above and since its out of scope.
