### ISSUE TITLE
[Feature] Smaller docker image

### ISSUE THREAD

**Issue by lonix1** [microsoft/playwright-dotnet#2694]
## PROBLEM

The official [docker image](https://github.com/microsoft/playwright-dotnet/blob/main/utils/docker/Dockerfile.jammy) is a whopping 3GiB in size.

That is a real problem:
- We customise the image (e.g. update to net7.0) and add our own app in there. So we have dozens of extra "overlay2" layers each about 3GiB in size, which clogs up our server daily.
- Most operations are very slow, especially in CI. It takes time to copy / update / etc. such a large image and so every pipeline takes forever.

## SOLUTION

*Please consider releasing a leaner image.*

If possible then alpine; otherwise debian.

Also, it would be nice to have an image with only chromium (which would significantly reduce the size). That could be setup as a matrix docker build, so we could download per-browser images, or an all-in-one image. If not possible, then at least provide guidance how we can strip down the image to remove unnecessary browsers.

**Comment by mxschmitt** [comment]
Supporting alpine is unfortunately outside of the scope for the project, since we don't compile browsers for this platform. Having a Docker image for Debian is tracked here: https://github.com/microsoft/playwright-dotnet/issues/2680

> Also, it would be nice to have an image with only chromium (which would significantly reduce the size)

I recommend filing a separate feature request for it, this sounds helpful.

> If not possible, then at least provide guidance how we can strip down the image to remove unnecessary browsers.

So far we recommend building your own image, which you can do either by downloading Playwright manually over nuget and invoking the cli to do: ["install --with-deps"](https://playwright.dev/dotnet/docs/browsers#install-system-dependencies) or you checkout our repository and use our publishing [scripts](https://github.com/microsoft/playwright-dotnet/blob/main/utils/docker/build.sh).

**Comment by mxschmitt** [comment]
Thanks for the suggestion! This indeed makes it 570MB smaller for me: https://github.com/microsoft/playwright-dotnet/pull/2695
