### ISSUE TITLE
[Feature] "runsettings" file for library mode

### ISSUE THREAD

**Issue by lonix1** [microsoft/playwright-dotnet#2728]
I use Playwright in "library mode", and I only use Chromium.

Whenever a new version is available, it warns me to run `playright.ps1 install` - but that installs all the browsers.

In various issues here and in the [docs](https://playwright.dev/dotnet/docs/browsers) I noted that it's possible to specify only Chromium, by using a "runsettings" [file](https://playwright.dev/dotnet/docs/release-notes#new-runsettings-file-support). But it seems that is only for testing, not library mode.

Is it possible to use a runsettings file for library mode too, so that I can specify that I only want chromium? If not, could that be a feature request please?

**Comment by mxschmitt** [comment]
When you are using the Library, you can manually create your testing framework, to launch different browsers, with different launch/context options. See here:

- https://playwright.dev/dotnet/docs/api/class-browser#browser-new-context
- https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch

So this is something which can be only solved in user-land rather than on our side. Would that work for you?

**Comment by campersau** [comment]
I addition to that the docs also mention that you can specify a browser when doing `playwright.ps1 install chromium` (they use `webkit` as an example but `chromium` works too).

In addition to that you can install the browser via API at runtime as mentioned here: https://playwright.dev/dotnet/docs/browsers#install-browsers-via-api
And there you can also pass a second parameter like this:
```c#
Microsoft.Playwright.Program.Main(new[] {"install", "chromium"});
```
Which means you can customize this parameter as you like e.g. instead of hard coding the value, check the the environment variables or the runsettings file.

**Comment by campersau** [comment]
> So are you stating that I can indeed use a runsettings file?

No, not directly, but you can specify the browser manuallly like this: `playwright.ps1 install chromium`

Or you can do it in your code via:
```c#
Microsoft.Playwright.Program.Main(new[] {"install", "chromium"});
```
And in the code you could do the `.runsettings` check manually like this (pseudo code):
```c#
var xml = File.ReadAllText(".runsettings");
var doc = XDocument.Parse(xml);
var browser = doc.Root.Element("...").Text;
Microsoft.Playwright.Program.Main(new[] {"install", browser});
```

**Comment by campersau** [comment]
You can check out these docker files which pre install everything that is needed for Playwright: https://github.com/microsoft/playwright-dotnet/tree/main/utils/docker
