### ISSUE TITLE
[Question] Can i run my test on different executors?

### ISSUE THREAD

**Issue by SaveliyShur** [microsoft/playwright-dotnet#2865]

**Comment by SaveliyShur** [comment]
I read about sharding (https://playwright.dev/docs/test-sharding). Is it available for .net?

**Comment by mxschmitt** [comment]
Sharding is not available. Playwright for .NET does offer [MSTest/NUnit bindings](https://playwright.dev/dotnet/docs/intro) (this means what they offer is supported) or alternatively you consume the [library](https://playwright.dev/dotnet/docs/library) and create your own test-framework.

Closing by that since this bug tracker is for bugs only.
