### ISSUE TITLE
[Bug]: Missing playwright files since after 1.39.0 in Nuget Packages. (.playwright / node / .../ playwright...

### ISSUE THREAD

**Issue by awther** [microsoft/playwright-dotnet#2870]
### Version

1.41.2

### Steps to reproduce

Look at the extracted nuget packages from 1.39.0 forward.

Go inside the .playwright / node / platform (darwin-x64 -darwin-arm64 - linux-arm64 - linux-x64 - win32_x64) directory and look at the files listed.

You will see only some version of node for 1.40.0 forward. From 1.39.0 backwards, you will also see either playwright.sh or playwright.cmd.

Please add these files back to the nuget package. Some of use use them in our cicd pipeline to add playwright to our containers, etc.

Thanks!

### Expected behavior

I expect to see node and playwright

### Actual behavior

I see only node

### Additional context

Please add these files back to the nuget package. Some of use use them in our cicd pipeline to add playwright to our containers, etc.

### Environment

```Text
All environments are impacted. The issue is missing files in the nuget package.
```

**Comment by mxschmitt** [comment]
Closing by that. playwright.ps1 is the file we recommend when interacting with the CLI, this is our public API.

**Comment by serega404** [comment]
@mxschmitt 
Hello, why did you abandon the bash script? Installing PowerShell on Linux is a problem because PowerShell is not distributed in repositories. I am trying to make my Docker container as small as possible, but because of PowerShell (and the MS repository for Debian/Ubuntu), the size of my image increases significantly, as does the build time.
