### ISSUE TITLE
Where playwright writes verbose logging in .Net

### ISSUE THREAD

**Issue by kabdul-incomm** [microsoft/playwright-dotnet#2903]
### Please do not submit this issue.

- [X] I understand

**Comment by kabdul-incomm** [comment]
We have a unique issue, our application redirects a URL to partner URL and later partner redirects the customer to our application URL and I don't see this is happening for headless mode but when I run the same test in headed mode everything works fine. Need help in debugging the issue in headless mode.

**Comment by mxschmitt** [comment]
Have you tried using the Trace Viewer to debug the tests? https://playwright.dev/dotnet/docs/trace-viewer-intro

There you see how the page looked like during the test run, all the network requests, console logs etc.

**Comment by mxschmitt** [comment]
We need more to act on issues like this. Closing since this issue is not following the issue-template. The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see: 

- [The Playwright documentation](https://playwright.dev) 
- [Our Discord server](https://aka.ms/playwright/discord)

---

Feel free to re-file with something we can run locally.
