### ISSUE TITLE
[Feature]: Test ordering or test suite support

### ISSUE THREAD

**Issue by razigohar** [microsoft/playwright-dotnet#2986]
### 🚀 Feature Request

There is no support provided for test order or test suites in Playwright dotnet using MSTest.

### Motivation

The testing will be easier due to test ordering and all of the automation platforms also provide the functionality.

**Comment by mxschmitt** [comment]
This seems to be a feature request / question to the test-runner, in this case MSTest rather than to our test-harness aka. Microsoft.Playwright.MSTest. I think you might file [this](https://stackoverflow.com/questions/2255284/how-does-mstest-determine-the-order-in-which-to-run-test-methods) helpful or I recommend to file a feature request [here](https://github.com/microsoft/testfx) instead.
