### ISSUE TITLE
[Bug]: Blank screens visible on headless mode.

### ISSUE THREAD

**Issue by Kedar-Ghadge** [microsoft/playwright-dotnet#3021]
### Version

1.44.0

### Steps to reproduce

Example steps (replace with your own):
1. Clone my repo at https://github.com/Kedar-Ghadge/PlaywrightWithNunitCSharp.git
2. Make changes in `runsettings` file, change headless mode to true.
3. execute command dotnet test from the project's folder path
4. You should see blank screens come up without any taskbar icon for same.

### Expected behavior

No blank screens should occur.

### Actual behavior

Blank screens are occurring on test execution.

### Additional context

- If I put wrong spelling for true like instead of 'true' if I put 'ture' then no blank screen is occurring. 

### Environment

- Operating System: [Windows 11]
- CPU: [x64]
- Browser: [Chromium]
- .NET Version (TFM): [net8.0]
- Other info:

**Comment by campersau** [comment]
Looks similar to these issues:
- https://github.com/hardkoded/puppeteer-sharp/issues/2782
- https://github.com/puppeteer/puppeteer/issues/13121
- https://github.com/puppeteer/puppeteer/issues/13012
- https://stackoverflow.com/questions/78996364/chrome-129-headless-shows-blank-window

For me it looks like the issue is no longer present with chrome/edge 130.
I am supprised that I coulnd't find a playwright issue for it.

> If I put wrong spelling for true like instead of 'true' if I put 'ture' then no blank screen is occurring.

For me the test fail immediatly when using incorrect spelling.

**Comment by mxschmitt** [comment]
@Kedar-Ghadge have you tried a more recent Playwright version? e.g. 1.47?

**Comment by mxschmitt** [comment]
This means that updating won't help - since msedge still uses your system Microsoft Edge which you have installed.

You can try Microsoft Edge Beta / Dev if you need to use Edge and can't use Playwright's Chromium.

**Comment by mxschmitt** [comment]
I see that you don't use the latest Playwright version. The other folks in the issue suggest that updating the Playwright version should make it work with recent Microsoft Edge.

**Comment by Kedar-Ghadge** [comment]
@mxschmitt, it worked after upgrading playwright to 1.47.0 latest version. Thanks.
