### ISSUE TITLE
Unable to install browser dependencies for playwright within docker

### ISSUE THREAD

**Issue by hbkriz** [microsoft/playwright-dotnet#3040]
I am experiencing issues when I install browser dependencies for playwright test project via Dockerfile.

I ran the following within my Dockerfile:

RUN pwsh playwright.ps1 install-deps

Failed to fetch http://deb.debian.org/debian/dists/xxxxx/InRelease 503 Service Unavailable

Failed to install browser dependencies 8.323 Error: Installation process exited with code: 100
failed to solve: process "/bin/sh -c pwsh playwright.ps1 install-deps" did not complete successfully: exit code: 1

I ran playwright.ps1 install within Dcokerfile that worked without any issues. Is there a way to do package installation offline?

**Comment by mxschmitt** [comment]
503 Service Unavailable sounds like that deb.debian.org is down.

I'll close it for now since this is not a Playwright issue and most likely a temporary issue with the Debian apt mirror.

> I ran playwright.ps1 install within Dcokerfile that worked without any issues. Is there a way to do package installation offline?

https://playwright.dev/dotnet/docs/docker has all of the dependencies installed - there you don't need playwright.ps1 anymore.
