### ISSUE TITLE
Why there is a need for 2 (Playwright and NUnit) Adapters in dependencies

### ISSUE THREAD

**Issue by nithinbandaru1** [microsoft/playwright-dotnet#3043]
### Please do not submit this issue.

- [x] I understand

**Comment by mxschmitt** [comment]
It takes care of reading the values from the runsettings file / parameters.

**Comment by nithinbandaru1** [comment]
@mxschmitt Thanks for super fast reply. But I was not yet written my questions 😁. It would be really kind of you if you can address my questions.

**Comment by nithinbandaru1** [comment]
https://github.com/microsoft/playwright-dotnet/issues/2988
I guess Reqroll (Formally SpecFlow) framework based NuGet package would resolve my 4 point quite easily.

**Comment by mxschmitt** [comment]
1. Its not enough, since we have a custom logic to parse the runsettings file with the Playwright properties. This is what our TestAdapter takes care of. It does not modify default execution of NUnit or MSTest.
2. Internally yes, but this is an implementation detail. Internally we are communicating over stdin/stdout with it. With port we mean the .NET version of Playwright aka. a client.
3. There is no trx integration with Playwright test steps. Playwright for .NET is just a library. No additional integrations as of today. Tools like VSCode integration, UI Mode or HTML Reporter are Node.js only.
4. There are no plans for that as of today.
